const level1 = new Level(
    [
        new Fish_g(),
        new Fish_g(),
        new Fish_g(),
        new Fish_r(),
        new Fish_r(),
        new Fish_r(),
        new Fish_b(),
        new Fish_b(),
        new Fish_b(),
        new J_Fish_l(),
        new J_Fish_l(),
        new J_Fish_l(),
        new J_Fish_l(),
        new J_Fish_y(),
        new J_Fish_y(),
        new J_Fish_y(),
        new J_Fish_y(),
        new J_Fish_g_sd(),
        new J_Fish_g_sd(),
        new J_Fish_g_sd(),
        new J_Fish_p_sd(),
        new J_Fish_p_sd(),
        new J_Fish_p_sd(),
        new Endboss(),
    ],
    [
        new Light1(),
        new Light2(),
    ],
    [
        new BackgroundObject('img/3. Background/Layers/5. Water/D2.png', -720),
        new BackgroundObject('img/3. Background/Layers/4.Fondo 2/D2.png', -720),
        new BackgroundObject('img/3. Background/Layers/3.Fondo 1/D2.png', -720),
        new BackgroundObject('img/3. Background/Layers/2. Floor/D2.png', -720),
        new BackgroundObject('img/3. Background/Layers/5. Water/D1.png', 0),
        new BackgroundObject('img/3. Background/Layers/4.Fondo 2/D1.png', 0),
        new BackgroundObject('img/3. Background/Layers/3.Fondo 1/D1.png', 0),
        new BackgroundObject('img/3. Background/Layers/2. Floor/D1.png', 0),
        new BackgroundObject('img/3. Background/Layers/5. Water/D2.png', 720),
        new BackgroundObject('img/3. Background/Layers/4.Fondo 2/D2.png', 720),
        new BackgroundObject('img/3. Background/Layers/3.Fondo 1/D2.png', 720),
        new BackgroundObject('img/3. Background/Layers/2. Floor/D2.png', 720),

        new BackgroundObject('img/3. Background/Layers/5. Water/D1.png', 720 * 2),
        new BackgroundObject('img/3. Background/Layers/4.Fondo 2/D1.png', 720 * 2),
        new BackgroundObject('img/3. Background/Layers/3.Fondo 1/D1.png', 720 * 2),
        new BackgroundObject('img/3. Background/Layers/2. Floor/D1.png', 720 * 2),
        new BackgroundObject('img/3. Background/Layers/5. Water/D2.png', 720 * 3),
        new BackgroundObject('img/3. Background/Layers/4.Fondo 2/D2.png', 720 * 3),
        new BackgroundObject('img/3. Background/Layers/3.Fondo 1/D2.png', 720 * 3),
        new BackgroundObject('img/3. Background/Layers/2. Floor/D2.png', 720 * 3),
    ]
)